### ISSUE TITLE
docker run: `-p` argument needs to come before the `IMAGE_NAME`.

### ISSUE THREAD

**Issue by JanWaldhorn** [s1ntaxe770r/SSH-dockerfile#3]
Thanks for your work.

Unfortunately I had an error starting the image using the suggested code:

`docker run IMAGE_NAME -p 22:22`

This leads to:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "-p": executable file not found in $PATH: unknown.`

After some searching I found this post at [github](https://github.com/docker/for-linux/issues/561#issuecomment-483022978), according to which the `-p` argument must come before the `IMAGE_NAME`.

With `docker run -p 22:22 IMAGE_NAME ` it works for me.

**Comment by s1ntaxe770r** [comment]
Oh shoot, typo :). Thanks!

**Comment by s1ntaxe770r** [comment]
Thanks!! Updated the README
